### ISSUE TITLE
Bolding most (sometimes all) text

### ISSUE THREAD

**Issue by chekhovsnerfgun** [axoletl/not-br#12]
Hey, recently I've noticed whenever I convert a bunch of text on the not-br neocities page it often just bolds most (if not all) of it. 

Messing around with the sliders is... interesting. If I describe everything I've tried I'll be here all day, so let's just say I can't seem to find a position for the fixation & saccade sliders that doesn't cause excessive bolding, besides setting the fixation all the way to the left. Depending on the position of both, it bolds either all of the text or only after a certain number of words. I can't really figure out any rhyme or reason to it from a user perspective, and I don't have enough experience with JS to check the code.

I noticed it on my laptop (macOS 12.3, Firefox 101.0.1 & Safari 15.4), and it seems to happen on my phone as well (iOS 15.5, Firefox 101.1 & Safari 15.5).

(Also, I can't submit this without wholeheartedly thanking you for not-BR. It's an absolute life saver for me as someone with ADHD, you're doing humanity as a whole a massive service. Thank you, from the bottom of my heart.)

**Comment by chekhovsnerfgun** [comment]
Update: just tried it on Ubuntu (20.04, using Firefox 86.0) and had the same issue. I'm using Parallels 16.5.2 to run Ubuntu on the laptop I mentioned above, if that's of any relevance.

**Comment by axoletl** [comment]
heya! thanks for bringing this to my attention im a bit embarassed to see this was up for the last 2 weeks haha, ive put in a fix i was working on from the chrome extension and hopefully thatll resolve things, let me know how it is!

**Comment by chekhovsnerfgun** [comment]
No worries :) I just gave it a try and it seems to be fixed now, thanks so much!!
