### ISSUE TITLE
Deployment would be easier if there were a Makefile/CMakefile

### ISSUE THREAD

**Issue by jculpon** [axoletl/not-br#3]
Per README, this isn't packed for quick deployment by people unfamiliar with the tech stack involved. I believe it should be straightforward to modify a make/rake/cmake file to make this static generator deployable anywhere that speaks make clean; make; make deploy;

**Comment by axoletl** [comment]
honestly not 100% familiar with make or deploying with it on other sites and im not too sure what kind of packing is needed for something that is already down to just a css, html and js file. frankly ive only set this up insofar as i just drag the files right into the neocities uploader or using their deployment actions down the line. feel free to point me anywhere specifically and id love to take a look but i really am very new to this and only really putting it on here for people to do better with it!

**Comment by jculpon** [comment]
Well, do you want a pull request here or some other way of me fixing this issue?

**Comment by axoletl** [comment]
i dont feel there is an issue to be fixed? theres no build step or preprocessing step that needs to be automated, the production files are exactly as the source files are since there is no frameworks or tech stack needed

**Comment by jculpon** [comment]
OK, then I refuse to communicate further with axoletl/not-br, bye

**Comment by jculpon** [comment]
Rejected, please delete all contributions I have made to this repository ever.

**Comment by NotRanged** [comment]
what the fuck lol

**Comment by jculpon** [comment]
> what the fuck lol

What the fuck is: I don't want to be part of the project, thanks! I had found multiple security vulnerabilities in this project via my work on punchelvis/not-br, and since the community is resoundingly against setting this up so I can responsibly/ethically disclose them: I choose not to disclose them on the public github page.

**Comment by jculpon** [comment]
> honestly not 100% familiar with make or deploying with it on other sites and im not too sure what kind of packing is needed for something that is already down to just a css, html and js file. frankly ive only set this up insofar as i just drag the files right into the neocities uploader or using their deployment actions down the line. feel free to point me anywhere specifically and id love to take a look but i really am very new to this and only really putting it on here for people to do better with it!

This kind of packaging is necessary for me as someone who scans packages for vulnerabilities before passing them downstream to other users. If that is of no interest, cool. It was of interest to me as a packager/package-manager a couple weeks ago, but it s not now as either a maintainer nor a security researcher based on these interactions.
