### ISSUE TITLE
nil

### ISSUE THREAD

**Issue by jculpon** [axoletl/not-br#5]

**Comment by hlmartin** [comment]
respectfully, you've jumped on this repo with some pretty hyper-specific requests for someone who has admitted to being very new to all this, and then demanded all of your own comments be deleted when not acquiesced to.

to quote the [actual github community guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines):

> Be welcoming and open-minded - New users join our community each day. Some are well-established developers, while others are just beginning. Be open to other ideas and experience levels. Make room for opinions other than your own and be welcoming to new collaborators and those just getting started.

perhaps take a moment to consider explaining why a security.md or a makefile is important to you for this project, or why you're taking such issue to a small little pet project not following whatever guidelines you're referring to in this issue.

**Comment by Rexogamer** [comment]
you opened #3, they were confused/not entirely certain that a makefile was needed and your response was to... demand that they "delete your contributions" and close the issue. they were perfectly civil and your responses have been unnecessarily hostile.

you also opened #4 - they (somewhat dismissively but understandably) said that it wasn't needed and that they did it want any contact info there (a valid request!). you again closed the pr after asking for your contributions to be deleted. 

i get how your issues/prs being marked as wontfix might be upsetting, but please take a step back and remember that it's almost certainly nothing personal and that they probably have nothing against you specifically, just that your two requests so far were deemed unnecessary for a small project like this. 

i also fail to see any evidence of your last point on this repo...? please correct me if i'm wrong but there doesn't seem to be anything that suggests they don't understand the difference between these three concepts.

**Comment by jculpon** [comment]
I asked to opt out because I had other stuff to deal with, and I'm asking again: don't bug me about this, I thought it was cool, but don't think the tool is gonna grow in such a way that I could use it. If that's rude: sorry! I got COVID and don't want to deal with random github pings. I deal with enough community managment in my paying jobs.
