### ISSUE TITLE
Feature Proposal: Copy as Markdown button

### ISSUE THREAD

**Issue by dvanduzer** [axoletl/not-br#7]
On the most cursory search, I found this example of a full browser extension: https://github.com/yorkxin/copy-as-markdown

Even as a standalone web page, I think a "copy as markdown" function would be a pretty easy lift for not-br. I will try to find time to make a PR here if this sounds useful. 🙂

**Comment by axoletl** [comment]
this sounds interesting! looking at the extension though, it looks like all it does is grab the name of a website and its url in markdown, did you mean copying the converted not-br text as markdown instead?

**Comment by dvanduzer** [comment]
Yep, that's exactly what I mean. Copying the converted not-br text into the clipboard in Markdown format.

**Comment by axoletl** [comment]
that sounds good, im a bit tied up working on a browser extension implementation of not-br at the moment but if you feel up for it a pr would be welcome! ill probably also have to clean up the ui for it too but that can come afterwards

**Comment by axoletl** [comment]
addressed in https://github.com/axoletl/not-br/pull/8
