### ISSUE TITLE
Use GH Pages to host the site for more easy deployment

### ISSUE THREAD

**Issue by JulianusIV** [axoletl/not-br#9]
I dont know how you are currently hosting the website, or how you deploy it, so i cant tell if this would be easier for you, or if this is wanted, so no PR, but an issue.

on my [Fork](https://github.com/julianusiv/not-br) i set up the site to be hosted on Github pages (https://julianusiv.github.io/not-br/) in a seperate branch
due to how github pages work i had to copy over the contents of the public folder to the root folder of the repo, for which i set up a workflow in my main branch that will automatically update the pages branch ona new commit on main, which will also automaticall update the website

If this is something that you see as useful i can clean everything up and convert it to a PR, so you would only have to activate pages in the settings

**Comment by axoletl** [comment]
this is neat! if this was a site in an earlier stage id probably have done this instead, but i think most people have saved this neocities url at this point, and i like the community there.
deployment can probably be sped up by using something like https://github.com/marketplace/actions/deploy-to-neocities instead? i planned to put this in at some point but ive been busy

**Comment by JulianusIV** [comment]
> this is neat! if this was a site in an earlier stage id probably have done this instead, but i think most people have saved this neocities url at this point, and i like the community there. deployment can probably be sped up by using something like https://github.com/marketplace/actions/deploy-to-neocities instead? i planned to put this in at some point but ive been busy

oh i just realized that the neocities subdomain isnt yours lol
but in that case there would be either the possibility of using a redirect from neocities, or just implementing the workflow you sent, which would probably be easier than setting up pages at this point
but i dont know a lot about NC so i cant say anything about how stable they are or stuff like that.

**Comment by axoletl** [comment]
neocities has been fairly stable for me so far, and inclined to set up the workflow instead since redirecting can be confusing for people. will handle this in the next day or two
